"""Add period_log table

Revision ID: 56d7a478f3de
Revises: fc5d85bec8ca
Create Date: 2026-10-04 15:57:35.877416

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56d7a478f3de"
down_revision: str | Sequence[str] | None = "fc5d85bec8ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "period_log",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("period_start_date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "client_id", "period_start_date", name="uq_period_log_client_date"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("period_log")
    # ### end Alembic commands ###
