"""initial schema

Revision ID: 949da0c8b526
Revises:
Create Date: 2026-05-12 13:13:44.167552

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "949da0c8b526"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dietary_tag",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "exercise",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recipe",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "meal_type",
            sa.Enum("breakfast", "lunch", "dinner", "snack", name="mealtype"),
            nullable=False,
        ),
        sa.Column("protein", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("carbs", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("fat", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("serving_size", sa.String(length=100), nullable=False),
        sa.Column("preparation_notes", sa.Text(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("trainer", "client", name="userrole"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_email_active",
        "user",
        ["email"],
        unique=True,
        postgresql_where="is_active = true",
    )
    op.create_table(
        "ingredient",
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipe_dietary_tag",
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("dietary_tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dietary_tag_id"],
            ["dietary_tag.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id", "dietary_tag_id"),
    )
    op.create_table(
        "trainer_profile",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("specialization", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "client_profile",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column(
            "body_fat_percentage", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("fitness_goal", sa.String(length=255), nullable=True),
        sa.Column("onboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cycle_length_days", sa.Integer(), nullable=False),
        sa.Column("period_length_days", sa.Integer(), nullable=False),
        sa.Column("last_period_start", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainer_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "trainer_availability",
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("slot_start", sa.Time(), nullable=False),
        sa.Column("slot_end", sa.Time(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainer_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client_profile_dietary_tag",
        sa.Column("client_profile_id", sa.UUID(), nullable=False),
        sa.Column("dietary_tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_profile_id"],
            ["client_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dietary_tag_id"],
            ["dietary_tag.id"],
        ),
        sa.PrimaryKeyConstraint("client_profile_id", "dietary_tag_id"),
    )
    op.create_table(
        "daily_log",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column(
            "cycle_phase",
            sa.Enum(
                "menstrual", "follicular", "ovulatory", "luteal", name="cyclephase"
            ),
            nullable=False,
        ),
        sa.Column("hours_of_sleep", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "log_date", name="uq_daily_log_client_date"),
    )
    op.create_table(
        "exercise_log",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meal_log",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column(
            "meal_type",
            sa.Enum("breakfast", "lunch", "dinner", "snack", name="mealtype"),
            nullable=False,
        ),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("portion_quantity", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("portion_unit", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nutrition_plan",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainer_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_nutrition_plan_client_active",
        "nutrition_plan",
        ["client_id"],
        unique=True,
        postgresql_where="is_active = true",
    )
    op.create_table(
        "session",
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "confirmed", "completed", "cancelled", name="sessionstatus"
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainer_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training_plan",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainer_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_training_plan_client_active",
        "training_plan",
        ["client_id"],
        unique=True,
        postgresql_where="is_active = true",
    )
    op.create_table(
        "nutrition_plan_recipe",
        sa.Column("nutrition_plan_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column(
            "meal_type",
            sa.Enum("breakfast", "lunch", "dinner", "snack", name="mealtype"),
            nullable=False,
        ),
        sa.Column(
            "cycle_phase",
            sa.Enum(
                "menstrual", "follicular", "ovulatory", "luteal", name="cyclephase"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nutrition_plan_id"],
            ["nutrition_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint(
            "nutrition_plan_id", "recipe_id", "meal_type", "cycle_phase"
        ),
    )
    op.create_table(
        "training_plan_exercise",
        sa.Column("training_plan_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column(
            "cycle_phase",
            sa.Enum(
                "menstrual", "follicular", "ovulatory", "luteal", name="cyclephase"
            ),
            nullable=False,
        ),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("difficulty_level", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_plan_id"],
            ["training_plan.id"],
        ),
        sa.PrimaryKeyConstraint(
            "training_plan_id", "exercise_id", "cycle_phase", "day_of_week"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_plan_exercise")
    op.drop_table("nutrition_plan_recipe")
    op.drop_index(
        "ix_training_plan_client_active",
        table_name="training_plan",
        postgresql_where="is_active = true",
    )
    op.drop_table("training_plan")
    op.drop_table("session")
    op.drop_index(
        "ix_nutrition_plan_client_active",
        table_name="nutrition_plan",
        postgresql_where="is_active = true",
    )
    op.drop_table("nutrition_plan")
    op.drop_table("meal_log")
    op.drop_table("exercise_log")
    op.drop_table("daily_log")
    op.drop_table("client_profile_dietary_tag")
    op.drop_table("trainer_availability")
    op.drop_table("client_profile")
    op.drop_table("trainer_profile")
    op.drop_table("recipe_dietary_tag")
    op.drop_table("ingredient")
    op.drop_index(
        "ix_user_email_active", table_name="user", postgresql_where="is_active = true"
    )
    op.drop_table("user")
    op.drop_table("recipe")
    op.drop_table("exercise")
    op.drop_table("dietary_tag")
    # ### end Alembic commands ###
