"""Add user name fields and switch trainer availability to date-based slots

Revision ID: dc16e09ea7a1
Revises: 949da0c8b526
Create Date: 2026-09-08 16:24:05.490052

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc16e09ea7a1"
down_revision: str | Sequence[str] | None = "949da0c8b526"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trainer_availability", sa.Column("slot_date", sa.Date(), nullable=False)
    )
    op.drop_column("trainer_availability", "day_of_week")
    op.add_column("user", sa.Column("first_name", sa.String(length=255), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    op.add_column(
        "trainer_availability",
        sa.Column("day_of_week", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("trainer_availability", "slot_date")
    # ### end Alembic commands ###
