"""Make ingredient a shared library table via RecipeIngredient association

Revision ID: fc5d85bec8ca
Revises: dc16e09ea7a1
Create Date: 2026-09-24 16:21:54.319351

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc5d85bec8ca"
down_revision: str | Sequence[str] | None = "dc16e09ea7a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_ingredient",
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(None, "ingredient", ["name"])
    op.drop_constraint(
        op.f("ingredient_recipe_id_fkey"), "ingredient", type_="foreignkey"
    )
    op.drop_column("ingredient", "recipe_id")
    op.drop_column("ingredient", "quantity")
    op.drop_column("ingredient", "unit")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredient",
        sa.Column("unit", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ingredient",
        sa.Column(
            "quantity",
            sa.NUMERIC(precision=8, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ingredient",
        sa.Column("recipe_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("ingredient_recipe_id_fkey"), "ingredient", "recipe", ["recipe_id"], ["id"]
    )
    op.drop_constraint(None, "ingredient", type_="unique")
    op.drop_table("recipe_ingredient")
    # ### end Alembic commands ###
